# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool: default

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'CaseBuddy Release'
  buildPath: '$(System.DefaultWorkingDirectory)\Applications\CaseBuddy\bin\$(buildPlatform)\Release'

steps:
- task: PowerShell@2
  displayName: 'Get project version for ClickOnce'
  inputs:
    targetType: 'inline'
    script: |
      [xml]$doc = Get-Content -Path .\Applications\CaseBuddy\CaseBuddy.csproj
      $version = ([string]$doc.Project.PropertyGroup.ApplicationVersion -Replace "\.", "_").Trim()
      $installUrl = ([string]$doc.Project.PropertyGroup.InstallUrl).Trim()
      $ring = (Select-String '([^\/]+\/?$)' -Input $installUrl).Matches.Value.TrimEnd('/')

      Write-Output "##vso[task.setvariable variable=clickOnceVersion]$version"
      Write-Output "##vso[task.setvariable variable=deploymentRing]$ring"

- task: CredScan@2
  inputs:
    toolMajorVersion: 'V2'
    outputFormat: 'sarif'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build project'
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/target:publish'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: EsrpCodeSigning@1
  displayName: 'Codesign step 1 (binaries)'
  condition: ne(variables['deploymentRing'], 'alpha')
  inputs:
    ConnectedServiceName: 'codesign'
    FolderPath: '$(buildPath)\app.publish\Application Files\CaseBuddy64_$(clickOnceVersion)'
    Pattern: 'CaseBuddy64.exe,CaseSummary.dll,CSSVAAppLib.dll,DiagManager.dll,KWSharedUI.dll,MexBuddy.dll,MSDN.HtmlEditorControl.dll,QAMDashboard.dll,roster.dll,ServiceDeskAPI.dll,ServiceDeskUI.dll,UEXTitlerProxy.dll'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
          "keyCode": "CP-230012",
          "operationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd sha256"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            }
          ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: CmdLine@2
  displayName: 'Mage run 1 (manifest)'
  condition: ne(variables['deploymentRing'], 'alpha')
  inputs:
    script: '"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\mage.exe" -u "$(buildPath)\app.publish\Application Files\CaseBuddy64_$(clickOnceVersion)\CaseBuddy64.exe.manifest"'

- task: EsrpCodeSigning@1
  displayName: 'Codesign step 2 (manifest)'
  condition: ne(variables['deploymentRing'], 'alpha')
  inputs:
    ConnectedServiceName: 'codesign'
    FolderPath: '$(buildPath)\app.publish\Application Files\CaseBuddy64_$(clickOnceVersion)'
    Pattern: '*.manifest'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
          {
              "KeyCode" : "CP-232959",
              "OperationCode" : "magesignsha256rfc3161",
              "Parameters" : {
                  "OpusName" : "Microsoft",
                  "OpusInfo" : "http://www.microsoft.com"
              },
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          },
          {
              "KeyCode" : "CP-232959",
              "OperationCode" : "MageVerifySHA256",
              "Parameters" : {},
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: CmdLine@2
  displayName: 'Mage run 2 (clickonce)'
  condition: ne(variables['deploymentRing'], 'alpha')
  inputs:
    script: '"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\mage.exe" -u $(buildPath)\app.publish\CaseBuddy64.application -appm "$(buildPath)\app.publish\Application Files\CaseBuddy64_$(clickOnceVersion)\CaseBuddy64.exe.manifest"'

- task: EsrpCodeSigning@1
  displayName: 'Codesign step 3 (clickonce)'
  condition: ne(variables['deploymentRing'], 'alpha')
  inputs:
    ConnectedServiceName: 'codesign'
    FolderPath: '$(buildPath)\app.publish'
    Pattern: '*.application'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
          {
              "KeyCode" : "CP-232959",
              "OperationCode" : "magesignsha256rfc3161",
              "Parameters" : {
                  "OpusName" : "Microsoft",
                  "OpusInfo" : "http://www.microsoft.com"
              },
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          },
          {
              "KeyCode" : "CP-232959",
              "OperationCode" : "MageVerifySHA256",
              "Parameters" : {},
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: DeleteFiles@1
  displayName: 'Remove obsolete files'
  inputs:
    SourceFolder: '$(buildPath)\app.publish'
    Contents: |
      CaseBuddy64.exe
      CodeSignSummary-*.md
      **\CodeSignSummary-*.md

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(buildPath)\app.publish\*'
    azureSubscription: 'Azure Storage (CaseBuddy)'
    Destination: 'AzureBlob'
    storage: 'casebuddy'
    ContainerName: 'install'
    BlobPrefix: 'x64/$(deploymentRing)'