name: Release

on:
  push:
    tags: [v*]

jobs:
  release:
    runs-on: windows-latest
    outputs: 
      output1: ${{ steps.version.outputs.full }}

    steps:

      - name: Check Version Format in Tag
        uses: nowsprinting/check-version-format-action@v4.0.3

      - name: Version tag only step
        run: |
          echo "Found valid version format in tag!"
          echo "Full version: ${{ steps.version.outputs.full }}"
          # echo "Major version: ${{ steps.version.outputs.major }}"
          # echo "Major with pre-release: ${{ steps.version.outputs.major_prerelease }}"
        if: steps.version.outputs.is_valid == 'true'
    
            

     # - name: Checkout code
     #   uses: actions/checkout@v3

      # - name: Setup Git
      #   run: |
      #     git config --global url."https://user:${{ secrets.GITHUB_TOKEN }}@github".insteadOf https://github
      #     git config --global user.name github-actions
      #     git config --global user.email github-actions@github.com          

      - name: Run release script
        shell: pwsh
        run: ./SupportingFiles/release.ps1 ${{ steps.version.outputs.full }}
